//! TOTP **recovery codes** — the way back in when the authenticator is gone. See `docs/AUTH.md` §5i.
//!
//! A set of single-use codes is issued when a user enrols in 2FA (and can be regenerated from the
//! profile page). At `/login/totp` one can be submitted in place of the 6-digit code, which completes
//! the login and marks that code used. Without them, a lost phone means the account is reachable only
//! by a manager disabling its 2FA — which is fine for staff with an IT department and useless for
//! everyone else.
//!
//! **Hashed, but not with argon2, on purpose.** The codes here are generated by `issue` with ~49
//! bits of entropy, so the thing argon2 exists for — making each guess at a *human-chosen*, low-entropy
//! secret expensive — buys nothing: an attacker cannot enumerate a 49-bit space however cheap the hash
//! is. What a slow hash *would* cost is real, and paid by the defender: a submitted code has to be
//! matched against a user's whole set, so ten argon2 verifications (~190 MiB transient, most of a
//! second) on the **unauthenticated** login path, per attempt. A single SHA-256 instead makes the
//! lookup one indexed equality match — O(1), no comparison loop, nothing to time.
//!
//! The hash is domain-separated by user id, so a row lifted from one account cannot be replayed against
//! another, and codes are normalized before hashing (`normalize`) so formatting a code the way it was
//! displayed (`abcde-fghij`) or typing it in caps still matches.

use sea_orm::sea_query::OnConflict;
use sea_orm::ActiveValue::Set;
use sea_orm::{ColumnTrait, DatabaseConnection, DbErr, EntityTrait, PaginatorTrait, QueryFilter};
use sha2::{Digest, Sha256};

/// How many codes a set contains. Ten is the near-universal choice: enough that losing a couple to
/// paper accidents doesn't matter, few enough to print on one line each.
pub const SET_SIZE: usize = 10;

/// Characters in a code. Crockford-style: no `I`, `L`, `O` or `U`, so nothing is misread as `1`/`0` and
/// no code can spell an unfortunate word. 32 symbols → 5 bits each.
const ALPHABET: &[u8] = b"abcdefghjkmnpqrstvwxyz23456789";
/// Characters per code. 10 × log2(30) ≈ 49 bits — far beyond guessing, short enough to retype.
const CODE_LEN: usize = 10;

/// One unused-or-used recovery code. Table `auth_totp_recovery`, `SET_SIZE` rows per enrolled user.
///
/// `code_hash` is a SHA-256 of `user_id:code` (see the module docs) — a hash of a credential, so treat
/// it as one: there is no reason to register this entity in an admin panel, and nothing an operator can
/// do with a row except delete it (which the "generate new codes" button does properly).
pub mod entity {
    use sea_orm::entity::prelude::*;

    #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, serde::Serialize, serde::Deserialize)]
    #[sea_orm(table_name = "auth_totp_recovery")]
    pub struct Model {
        #[sea_orm(primary_key)]
        pub id: i32,
        pub user_id: i32,
        /// SHA-256 of `user_id:normalized_code`, lowercase hex.
        pub code_hash: String,
        /// Unix seconds the set was issued.
        pub created_at: i64,
        /// Unix seconds this code was spent, or `None` while it is still usable. Kept rather than
        /// deleted so "you used a recovery code" is visible after the fact; a whole set is replaced on
        /// regeneration and removed when 2FA is turned off, so rows never accumulate.
        pub used_at: Option<i64>,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}
}

/// Hash a code for storage/lookup, domain-separated by the account it belongs to.
fn hash(user_id: i32, code: &str) -> String {
    let mut h = Sha256::new();
    h.update(user_id.to_string().as_bytes());
    h.update(b":");
    h.update(normalize(code).as_bytes());
    h.finalize().iter().map(|b| format!("{b:02x}")).collect()
}

/// Fold a submitted code to its canonical form: lowercase, and with the grouping hyphens, spaces and
/// any other punctuation a user may have copied along stripped out. Nothing else is removed, so a
/// genuinely wrong code stays wrong.
pub fn normalize(code: &str) -> String {
    code.chars().filter(|c| c.is_ascii_alphanumeric()).map(|c| c.to_ascii_lowercase()).collect()
}

/// Format a code the way it is shown to the user: `abcde-fghij`, which is easier to read off paper and
/// which [`normalize`] undoes on the way back in.
pub fn display(code: &str) -> String {
    let code = normalize(code);
    if code.len() == CODE_LEN {
        format!("{}-{}", &code[..CODE_LEN / 2], &code[CODE_LEN / 2..])
    } else {
        code
    }
}

/// A fresh set of [`SET_SIZE`] codes, in the plaintext form to show the user **once**.
fn fresh_codes() -> Vec<String> {
    use rand_core::{OsRng, RngCore};
    (0..SET_SIZE)
        .map(|_| {
            let mut out = String::with_capacity(CODE_LEN);
            for _ in 0..CODE_LEN {
                // Rejection-free because 30 doesn't divide 256 evenly but the bias is negligible at
                // this entropy; draw a fresh byte per character from the OS CSPRNG.
                let idx = (OsRng.next_u32() % ALPHABET.len() as u32) as usize;
                out.push(ALPHABET[idx] as char);
            }
            out
        })
        .collect()
}

/// Issue a new set for `user_id`, **replacing** any existing one, and return the plaintext codes to
/// show once. The old set stops working the moment this succeeds — which is the point: a user
/// regenerating because they think their codes leaked needs the leaked ones dead.
pub async fn issue(db: &DatabaseConnection, user_id: i32) -> Result<Vec<String>, DbErr> {
    clear(db, user_id).await?;
    let codes = fresh_codes();
    let now = super::now_secs();
    let rows: Vec<entity::ActiveModel> = codes
        .iter()
        .map(|c| entity::ActiveModel {
            user_id: Set(user_id),
            code_hash: Set(hash(user_id, c)),
            created_at: Set(now),
            used_at: Set(None),
            ..Default::default()
        })
        .collect();
    entity::Entity::insert_many(rows)
        .on_conflict(OnConflict::new().do_nothing().to_owned())
        .exec(db)
        .await?;
    Ok(codes)
}

/// Spend `code` for `user_id`: `true` when it matched an **unused** code of theirs, which is then marked
/// used. `false` for an unknown code, an already-spent one, or an empty submission.
///
/// One indexed lookup, because the hash is deterministic — no loop over the user's set, and so nothing
/// whose duration depends on how far through the set the match was.
pub async fn consume(db: &DatabaseConnection, user_id: i32, code: &str) -> bool {
    if normalize(code).is_empty() {
        return false;
    }
    let row = entity::Entity::find()
        .filter(entity::Column::UserId.eq(user_id))
        .filter(entity::Column::CodeHash.eq(hash(user_id, code)))
        .filter(entity::Column::UsedAt.is_null())
        .one(db)
        .await
        .ok()
        .flatten();
    let Some(row) = row else { return false };
    // Mark used rather than delete, so a spent code stays visible as evidence. Conditional on still
    // being unused, so two simultaneous submissions of the same code can't both win.
    let updated = entity::Entity::update_many()
        .col_expr(entity::Column::UsedAt, sea_orm::sea_query::Expr::value(super::now_secs()))
        .filter(entity::Column::Id.eq(row.id))
        .filter(entity::Column::UsedAt.is_null())
        .exec(db)
        .await;
    matches!(updated, Ok(r) if r.rows_affected == 1)
}

/// How many of `user_id`'s codes are still unused — what the profile page reports, and the number that
/// tells a user it is time to generate a new set.
pub async fn remaining(db: &DatabaseConnection, user_id: i32) -> u64 {
    entity::Entity::find()
        .filter(entity::Column::UserId.eq(user_id))
        .filter(entity::Column::UsedAt.is_null())
        .count(db)
        .await
        .unwrap_or(0)
}

/// Delete every code (used or not) belonging to `user_id`. Called when a set is regenerated and when
/// 2FA is switched off — codes are meaningless without a second factor to recover from, and leaving
/// them would let a later re-enrolment inherit a stale set the user has long since thrown away.
pub async fn clear(db: &DatabaseConnection, user_id: i32) -> Result<(), DbErr> {
    entity::Entity::delete_many()
        .filter(entity::Column::UserId.eq(user_id))
        .exec(db)
        .await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_set_is_ten_distinct_unambiguous_codes() {
        let codes = fresh_codes();
        assert_eq!(codes.len(), SET_SIZE);
        let unique: std::collections::HashSet<_> = codes.iter().collect();
        assert_eq!(unique.len(), SET_SIZE, "codes within a set must not repeat");
        for c in &codes {
            assert_eq!(c.len(), CODE_LEN);
            assert!(
                c.bytes().all(|b| ALPHABET.contains(&b)),
                "{c} must avoid characters that can be misread"
            );
            for bad in ['i', 'l', 'o', 'u', '0', '1'] {
                assert!(!c.contains(bad), "{c} contains the ambiguous {bad:?}");
            }
        }
        // Two sets must not coincide — that would mean the generator isn't random.
        assert_ne!(fresh_codes(), codes);
    }

    #[test]
    fn normalize_undoes_display_and_forgives_typing() {
        let code = "abcde23456";
        assert_eq!(display(code), "abcde-23456");
        for typed in ["abcde-23456", "ABCDE-23456", " abcde 23456 ", "abcde–23456", "abcde.23456"] {
            assert_eq!(normalize(typed), code, "{typed:?} should fold to the stored form");
        }
        // …but not so forgiving that a wrong code becomes right.
        assert_ne!(normalize("abcde-23455"), code);
        assert_eq!(normalize("---"), "", "punctuation alone is not a code");
    }

    #[test]
    fn the_hash_is_bound_to_one_account() {
        let code = "abcde23456";
        assert_eq!(hash(1, code), hash(1, "ABCDE-23456"), "the same code, however written");
        assert_ne!(hash(1, code), hash(2, code), "a row must not transplant between accounts");
        assert_ne!(hash(1, code), hash(1, "abcde23457"));
        assert_eq!(hash(1, code).len(), 64, "sha-256 as hex");
    }
}
